#############################################################################
# Makefile for building: pipedreamz
# Generated by qmake (1.07a) (Qt 3.3.3) on: Sat Dec 11 10:37:23 2004
# Project:  pipedreamz.pro
# Template: app
# Command: $(QMAKE) -o Makefile pipedreamz.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/qt/3/mkspecs/linux-g++ -I. -I. -Isrc -I$(QTDIR)/include
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = src/pipe.h \
		src/pipedreamz.h \
		src/water.h
SOURCES = src/main.cpp \
		src/pipe.cpp \
		src/pipedreamz.cpp \
		src/water.cpp
OBJECTS = main.o \
		pipe.o \
		pipedreamz.o \
		water.o \
		form1.o
FORMS = src/form1.ui
UICDECLS = src/form1.h
UICIMPLS = src/form1.cpp
SRCMOC   = src/moc_pipe.cpp \
		src/moc_pipedreamz.cpp \
		src/moc_water.cpp \
		src/moc_form1.cpp
OBJMOC = moc_pipe.o \
		moc_pipedreamz.o \
		moc_water.o \
		moc_form1.o
DIST	   = pipedreamz.pro
QMAKE_TARGET = pipedreamz
DESTDIR  = 
TARGET   = pipedreamz

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: pipedreamz.pro  /usr/qt/3/mkspecs/linux-g++/qmake.conf 
	$(QMAKE) -o Makefile pipedreamz.pro
qmake: 
	@$(QMAKE) -o Makefile pipedreamz.pro

dist: 
	@mkdir -p .tmp/pipedreamz && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/pipedreamz/ && ( cd `dirname .tmp/pipedreamz` && $(TAR) pipedreamz.tar pipedreamz && $(GZIP) pipedreamz.tar ) && $(MOVE) `dirname .tmp/pipedreamz`/pipedreamz.tar.gz . && $(DEL_FILE) -r .tmp/pipedreamz

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

main.o: src/main.cpp src/pipedreamz.h \
		src/pipe.h \
		src/water.h \
		src/form1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

pipe.o: src/pipe.cpp src/pipe.h \
		src/h.xpm \
		src/v.xpm \
		src/x.xpm \
		src/t1.xpm \
		src/t2.xpm \
		src/t3.xpm \
		src/t4.xpm \
		src/logost.xpm
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipe.o src/pipe.cpp

pipedreamz.o: src/pipedreamz.cpp src/pipedreamz.h \
		src/pipe.h \
		src/water.h \
		src/form1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pipedreamz.o src/pipedreamz.cpp

water.o: src/water.cpp src/water.h \
		src/pipedreamz.h \
		src/pipe.h \
		src/form1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o water.o src/water.cpp

src/form1.h: src/form1.ui 
	$(UIC) src/form1.ui -o src/form1.h

src/form1.cpp: src/form1.h src/form1.ui 
	$(UIC) src/form1.ui -i form1.h -o src/form1.cpp

form1.o: src/form1.cpp src/form1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form1.o src/form1.cpp

moc_pipe.o: src/moc_pipe.cpp  src/pipe.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pipe.o src/moc_pipe.cpp

moc_pipedreamz.o: src/moc_pipedreamz.cpp  src/pipedreamz.h src/pipe.h \
		src/water.h \
		src/form1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pipedreamz.o src/moc_pipedreamz.cpp

moc_water.o: src/moc_water.cpp  src/water.h src/pipe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_water.o src/moc_water.cpp

moc_form1.o: src/moc_form1.cpp  src/form1.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form1.o src/moc_form1.cpp

src/moc_pipe.cpp: $(MOC) src/pipe.h
	$(MOC) src/pipe.h -o src/moc_pipe.cpp

src/moc_pipedreamz.cpp: $(MOC) src/pipedreamz.h
	$(MOC) src/pipedreamz.h -o src/moc_pipedreamz.cpp

src/moc_water.cpp: $(MOC) src/water.h
	$(MOC) src/water.h -o src/moc_water.cpp

src/moc_form1.cpp: $(MOC) src/form1.h
	$(MOC) src/form1.h -o src/moc_form1.cpp

####### Install

install:  

uninstall:  

