######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 11 10:36:41 2004
######################################################################

TEMPLATE = app
DEPENDPATH += src
INCLUDEPATH += . src

# Input
HEADERS += src/pipe.h src/pipedreamz.h src/water.h
INTERFACES += src/form1.ui
SOURCES += src/main.cpp src/pipe.cpp src/pipedreamz.cpp src/water.cpp
